// skin.js — generated by SLOT FORGE（PixiJS 版表現層參數）
// 這份檔案只影響「畫面」，不影響機率：sprite 幀數/時長、中獎特效、噴錢數量、彩帶顏色都在這裡。
// 來源：美術動畫編輯器的設定；想微調也可以直接改這支檔案，重整頁面就生效。
const Skin = {
  "renderer": "pixi",
  "pixiVersion": "8.20.1",
  "sourceGame": "Hold&Win_20Lines_5x3",
  "rowOrder": "topDown",
  "layering": "global",
  "coinType": 20,
  "motionBlur": true,
  "winFx": {
    "scale": 1.15,
    "brightness": 1.3,
    "glow": "rgb(255, 215, 0)"
  },
  "popFx": {
    "scale": 1.15,
    "brightness": 1.5
  },
  "timing": {
    "reelDelay": 300,
    "spin": 2000,
    "spinTurbo": 1000,
    "fillers": 18,
    "stopPause": 100,
    "landBounce": 300,
    "pulse": 1,
    "pop": 0.8,
    "cellSpin": 2000,
    "cellSpinRand": 800,
    "cellSpinTurbo": 300,
    "cellFillers": 15,
    "cellFillersTurbo": 4,
    "cellCoinChance": 0.1
  },
  "coinText": {
    "number": {
      "size": 2.2
    },
    "MINI": {
      "size": 1.8,
      "glow": "#ff00ff"
    },
    "MINOR": {
      "size": 1.8,
      "glow": "#00ffff"
    },
    "MAJOR": {
      "size": 1.8,
      "glow": "#00ff00"
    },
    "GRAND": {
      "size": 2,
      "glow": "#ff8c00"
    }
  },
  "dim": {
    "brightness": 0.4,
    "grayscale": 0.4,
    "blur": 1.5,
    "fade": 300
  },
  "symbols": {
    "1": {
      "win": "pulse",
      "sprite": {
        "src": "s1_sprite.png",
        "frames": 28,
        "dur": 1,
        "loop": true
      },
      "z": 10,
      "zActive": 999,
      "zWin": 999
    },
    "2": {
      "win": "pulse",
      "sprite": {
        "src": "s2_sprite.png",
        "frames": 28,
        "dur": 1,
        "loop": true
      },
      "z": 10,
      "zActive": 999,
      "zWin": 999
    },
    "3": {
      "win": "pulse",
      "sprite": {
        "src": "s3_sprite.png",
        "frames": 28,
        "dur": 1,
        "loop": true
      },
      "z": 10,
      "zActive": 999,
      "zWin": 999
    },
    "4": {
      "win": "pulse",
      "sprite": {
        "src": "s4_sprite.png",
        "frames": 28,
        "dur": 1,
        "loop": true
      },
      "z": 10,
      "zActive": 999,
      "zWin": 999
    },
    "5": {
      "win": "pulse",
      "sprite": {
        "src": "s5_sprite.png",
        "frames": 28,
        "dur": 1,
        "loop": true
      },
      "z": 10,
      "zActive": 999,
      "zWin": 999
    },
    "6": {
      "win": "pulse",
      "z": 10,
      "zActive": 900,
      "zWin": 999
    },
    "7": {
      "win": "pulse",
      "z": 10,
      "zActive": 900,
      "zWin": 999
    },
    "8": {
      "win": "pulse",
      "z": 10,
      "zActive": 900,
      "zWin": 999
    },
    "9": {
      "win": "pulse",
      "z": 10,
      "zActive": 900,
      "zWin": 999
    },
    "10": {
      "win": "pulse",
      "z": 10,
      "zActive": 900,
      "zWin": 999
    },
    "11": {
      "win": "pulse",
      "sprite": {
        "src": "SCATTER_sprite.png",
        "frames": 28,
        "dur": 1.5,
        "loop": true
      },
      "widthScale": 1.15,
      "glow": {
        "color": "rgba(255, 215, 0, 0.8)",
        "blur": 10
      },
      "period": 0.8,
      "z": 500,
      "zActive": 800,
      "zWin": 999
    },
    "20": {
      "win": "pulse",
      "widthScale": 1.3,
      "glow": {
        "color": "rgba(255, 215, 0, 0.9)",
        "blur": 8
      },
      "fit": "contain",
      "alignY": "bottom",
      "offsetX": 0.025,
      "dimExempt": true,
      "z": 400,
      "zActive": 900,
      "zWin": 999
    }
  },
  "explosion": null,
  "effects": {
    "coinImg": "coin.png",
    "confettiColors": [
      "#ffd700",
      "#ff4500",
      "#00e5ff",
      "#7c4dff",
      "#27e07e"
    ],
    "confettiDurMin": 1.5,
    "confettiDurMax": 3.5,
    "tiers": {
      "big": {
        "coins": 20,
        "confetti": 50
      },
      "mid": {
        "coins": 40,
        "confetti": 50
      }
    }
  }
};

export default Skin;